services:
  api:
    container_name: hedera-twitter-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT:-3001}"]
      interval: 5s
      timeout: 20s
      retries: 10
    environment:
      - NODE_ENV=production
      - SQLITE_REBUILD=true 